spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://budgetdb-srv-ahmed.mysql.database.azure.com:3306/flexibleserverdb?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=ahmedadmin@budgetdb-srv-ahmed
spring.datasource.password=Fathia!222
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
