name: Deploy Backend + Frontend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # ================================
      # BACKEND SPRING BOOT
      # ================================
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend
        working-directory: ./budget-backend-ahmed
        run: mvn clean package --no-transfer-progress

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'budget-backend-ahmed'                  # Ton App Service backend
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ./budget-backend-ahmed/target/BPDBackEnd-1.0.jar

      # ================================
      # FRONTEND ANGULAR
      # ================================
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./budget-frontend           # Ton dossier frontend
        run: npm install

      - name: Build frontend
        working-directory: ./budget-frontend
        run: npm run build -- --prod

      - name: Deploy frontend to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBAPP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./budget-frontend/dist"       # Angular build output
          output_location: "."
