name: Build and Deploy Spring Boot to Azure Web App

on:
  push:
    branches:
      - main  # Branche qui déclenche le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build le JAR avec Maven
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4. Upload le JAR comme artifact (optionnel)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: BPDBackEnd-JAR
          path: target/*.jar

      # 5. Deploy vers Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'budget-backend-ahmed'        # Nom de ton App Service
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
